// Generated by study/tests/make-study-java.mjs from content/study/*-bank.json. Do not edit by hand.
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.net.URI;
import java.nio.file.Files;
import java.util.List;
import java.util.function.Supplier;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

public class StudyCheck {
    static String typed(int v) { return "int:" + v; }
    static String typed(double v) { return "double:" + v; }
    static String typed(String v) { return "String:" + v; }
    static class Player {
        private String name;
        private int score;
        public Player(String startName, int startScore) { name = startName; score = startScore; }
        public String getName() { return name; }
        public int getScore() { return score; }
        public void addScore(int amount) { score += amount; }
    }
    static double area(double width, int sides) { return width * sides; }
    static int roll(int sides) { return (int) (Math.random() * sides) + 1; }

    static String e0() { double avg = (90 + 85 + 81) / 3; return typed(avg); }
    static String e1() { int x = 5 / 0; return typed(x); }
    static String e3() { double d = 5 / 0.0; return typed(d); }
    static String e4() { int x = 5 / 2; return typed(x); }
    static String e20() { return typed(1 / 0); }
    static String e29() { double ratio = 3 / 4; return typed(ratio); }
    static String e31() { int a = 90; int b = 7; int c = 4; return typed(a / b / c); }
    static String e32() { return typed((double) 17 / 4); }
    static String e33() { return typed((double) (17 / 4)); }
    static String e34() { return typed((int) 9.99 + (int) 0.5); }
    static String e35() { return typed(-17 / 5); }
    static String e36() { return typed(-17 % 5); }
    static String e37() { return typed(20 - 12 / 4 * 2 + 7 % 3); }
    static String e38() { int total = 7384; return typed(total % 3600 / 60); }
    static String e39() { int code = 4829; return typed(code / 10 % 10); }
    static String e40() { return typed(Integer.MAX_VALUE + 1); }
    static String e41() { int sum = 17; int count = 4; double avg = (double) sum / count; return typed(avg); }
    static String e42() { int sum = 17; int count = 4; double avg = (double) (sum / count); return typed(avg); }
    static String e43() { int sum = 17; int count = 4; double avg = sum / count * 1.0; return typed(avg); }
    static String e45() { return typed(5 / 2); }
    static String e46() { return typed((double) (5 / 2)); }
    static String e47() { return typed(5 / 2.0); }
    static String e48() { return typed((int) 5.0 / 2); }
    static String e49() { return typed(7 % 3 * 2); }
    static String e50() { return typed((int) 3.99); }
    static void o51() {
        System.out.print("Rain");
        System.out.println("bow " + "Road");
        System.out.println("Sun" + "  set");
    }
    static void o52() {
        System.out.println("one\ttwo\nthree\\four");
    }
    static void o53() {
        System.out.println("He said \"go\"");
    }
    static void o55() {
        System.out.println("He said \"go");
    }
    static String e57() { int y = 3; int z = 4; return typed("Total: " + y + z); }
    static String e58() { int y = 3; int z = 4; return typed(y + z + " total"); }
    static String e59() { int x = 10; int y = 5; return typed("" + x + y); }
    static String e60() { return typed("Area: " + 3 * 4); }
    static String e61() { return typed("Half: " + 7 / 2); }
    static String e62() { return typed("Score: " + 8 + 2); }
    static String e63() { return typed(8 + 2 + ""); }
    static String e64() { int a = 2; int b = 5; return typed("Sum: " + (a + b)); }
    static String e65() { int a = 2; int b = 5; return typed(("Sum: " + a) + b); }
    static String e66() { int a = 2; int b = 5; return typed("Sum: " + "" + a + b); }
    static String e67() { int a = 2; int b = 5; return typed(a + b + "Sum: "); }
    static void o68() {
        System.out.println(1 + 2 + "3" + 4 + 5);
    }
    static void o69() {
        String name = "Kai";
        System.out.print("Hi, ");
        System.out.print(name);
        System.out.println("!");
        System.out.println("Bye");
    }
    static void o70() {
        System.out.print("a");
        System.out.print("b");
    }
    static String e71() { return "String:" + "Good Morning".substring(2, 7); }
    static String e72() { return "String:" + "Good Morning".substring(5); }
    static String e73() { return "String:" + "planet".substring(6); }
    static String e74() { return "String:" + "planet".substring(3, 7); }
    static String e75() { return "int:" + "Hi there".length(); }
    static String e76() { return "int:" + "Robinson".indexOf("bin"); }
    static String e77() { return "int:" + "Robinson".indexOf("son"); }
    static String e78() { return "int:" + "Robinson".indexOf("Son"); }
    static String e79() { return "int:" + "banana".indexOf("na"); }
    static String e84() { return "String:" + "planet".substring(2, 4); }
    static void o85() {
        String full = "Ada Lovelace";
        System.out.print(full.substring(0, full.indexOf(" ")));
    }
    static void o86() {
        String full = "Ada Lovelace";
        System.out.print(full.substring(1, full.indexOf(" ")));
    }
    static void o87() {
        String full = "Ada Lovelace";
        System.out.print(full.substring(0, full.indexOf(" ") - 1));
    }
    static void o88() {
        String full = "Ada Lovelace";
        System.out.print(full.substring(full.indexOf(" ")));
    }
    static void o89() {
        String s = "Lin Wei";
        int sp = s.indexOf(" ");
        System.out.println(s.substring(sp + 1) + ", " + s.substring(0, sp));
    }
    static int r98(double r) { return (int) (r * 8) + 3; }
    static int r99(double r) { return (int) (r * 6) + 10; }
    static int r100(double r) { return (int) (r * 11) + 20; }
    static int r101(double r) { return (int) (r * 10) + 20; }
    static int r102(double r) { return (int) r * 11 + 20; }
    static int r103(double r) { return (int) (r * 30) + 20; }
    static int r104(double r) { return (int) r * 6 + 1; }
    static int r105(double r) { return (int) (r * 6) + 1; }
    static String e116() { return typed(Math.pow(3, 2)); }
    static String e117() { return typed(Math.abs(-7) / 2); }
    static String e118() { return typed(Math.sqrt(25) + 1); }
    static void o119() {
        Player a = new Player("Ana", 10);
        Player b = a;
        b.addScore(5);
        System.out.println(a.getScore());
    }
    static void o120() {
        Player a = new Player("Ana", 10);
        Player b = new Player("Ana", 10);
        b.addScore(5);
        System.out.println(a.getScore() + " " + b.getScore());
    }
    static void o121() {
        Player a = new Player("Ana", 10);
        Player b = a;
        a = new Player("Bo", 3);
        b.addScore(1);
        System.out.println(a.getName() + " " + b.getScore());
    }
    static void o122() {
        Player p = null;
        System.out.println(p.getScore());
    }
    static void o123() {
        String s = new String("hi");
        String t = new String("hi");
        System.out.println(s.equals(t) + " " + (s == t));
    }
    static void o124() {
        Player a = new Player("Ana", 10);
        Player b = new Player("Bo", 4);
        Player c = b;
        b = a;
        c.addScore(1);
        System.out.println(a.getScore() + " " + b.getScore() + " " + c.getScore());
    }
    static void o125() {
        Player a = new Player("Ana", 10);
        Player b = a;
        a = null;
        System.out.println(b.getScore());
    }
    static void o126() {
        String w = "hello";
        w.substring(1);
        System.out.println(w);
    }
    static void o127() {
        String w = "hello";
        w = w.substring(1);
        System.out.println(w);
    }

    static int passed = 0, failed = 0;

    static void check(String label, String expected, Supplier<String> actual) {
        String got;
        try { got = actual.get(); } catch (ArithmeticException e) { got = "throws:ArithmeticException"; }
          catch (StringIndexOutOfBoundsException e) { got = "throws"; }
        if (got.equals(expected)) passed++;
        else { failed++; System.out.println("FAIL " + label + ": Java gives " + show(got) + ", bank says " + show(expected)); }
    }

    static String capture(Runnable r) {
        PrintStream old = System.out;
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        System.setOut(new PrintStream(buf, true));
        try { r.run(); } finally { System.setOut(old); }
        return buf.toString().replace(System.lineSeparator(), "\n");
    }

    static String thrown(Runnable r) {
        try { capture(r); return "no exception"; } catch (RuntimeException e) { return e.getClass().getSimpleName(); }
    }

    static void compileCheck(JavaCompiler javac, String label, String code, String className, boolean shouldCompile) throws Exception {
        JavaFileObject src = new SimpleJavaFileObject(URI.create("string:///" + className + ".java"), JavaFileObject.Kind.SOURCE) {
            @Override public CharSequence getCharContent(boolean ignoreEncodingErrors) { return code; }
        };
        String out = Files.createTempDirectory("snip").toString();
        boolean ok = javac.getTask(null, null, new DiagnosticCollector<JavaFileObject>(), List.of("-d", out), null, List.of(src)).call();
        if (ok == shouldCompile) passed++;
        else { failed++; System.out.println("FAIL " + label + ": Java " + (ok ? "compiles" : "rejects") + " it, bank says it " + (shouldCompile ? "compiles" : "does not")); }
    }

    static String show(String s) { return "\"" + s.replace("\n", "\\n").replace("\t", "\\t") + "\""; }

    public static void main(String[] args) throws Exception {
        check("u1-run-logic [expr]", "double:85.0", () -> e0());
        check("u1-run-crash [expr]", "throws:ArithmeticException", () -> e1());
        check("u1-run-crash [expr]", "double:Infinity", () -> e3());
        check("u1-run-crash [expr]", "int:2", () -> e4());
        check("u1-run-compiles [expr]", "throws:ArithmeticException", () -> e20());
        check("u1-num-ratio [expr]", "double:0.0", () -> e29());
        check("u1-num-chain [expr]", "int:3", () -> e31());
        check("u1-num-cast1 [expr]", "double:4.25", () -> e32());
        check("u1-num-cast2 [expr]", "double:4.0", () -> e33());
        check("u1-num-trunc [expr]", "int:9", () -> e34());
        check("u1-num-negdiv [expr]", "int:-3", () -> e35());
        check("u1-num-negmod [expr]", "int:-2", () -> e36());
        check("u1-num-prec [expr]", "int:15", () -> e37());
        check("u1-num-time [expr]", "int:3", () -> e38());
        check("u1-num-digit [expr]", "int:2", () -> e39());
        check("u1-num-overflow [expr]", "int:-2147483648", () -> e40());
        check("u1-num-repair [expr]", "double:4.25", () -> e41());
        check("u1-num-repair [expr]", "double:4.0", () -> e42());
        check("u1-num-repair [expr]", "double:4.0", () -> e43());
        check("u1-num-mc [expr]", "int:2", () -> e45());
        check("u1-num-mc [expr]", "double:2.0", () -> e46());
        check("u1-num-mc [expr]", "double:2.5", () -> e47());
        check("u1-num-mc [expr]", "int:2", () -> e48());
        check("u1-num-prec-tf [expr]", "int:2", () -> e49());
        check("u1-num-round-tf [expr]", "int:3", () -> e50());
        check("u1-out-print [output]", "Rainbow Road\nSun  set\n", () -> capture(StudyCheck::o51));
        check("u1-out-lines [output]", "one\ttwo\nthree\\four\n", () -> capture(StudyCheck::o52));
        check("u1-out-quote [output]", "He said \"go\"\n", () -> capture(StudyCheck::o53));
        check("u1-out-quote [output]", "He said \"go\n", () -> capture(StudyCheck::o55));
        check("u1-out-cat1 [expr]", "String:Total: 34", () -> e57());
        check("u1-out-cat2 [expr]", "String:7 total", () -> e58());
        check("u1-out-cat3 [expr]", "String:105", () -> e59());
        check("u1-out-cat4 [expr]", "String:Area: 12", () -> e60());
        check("u1-out-cat5 [expr]", "String:Half: 3", () -> e61());
        check("u1-out-explain [expr]", "String:Score: 82", () -> e62());
        check("u1-out-explain [expr]", "String:10", () -> e63());
        check("u1-out-repair [expr]", "String:Sum: 7", () -> e64());
        check("u1-out-repair [expr]", "String:Sum: 25", () -> e65());
        check("u1-out-repair [expr]", "String:Sum: 25", () -> e66());
        check("u1-out-repair [expr]", "String:7Sum: ", () -> e67());
        check("u1-out-mc [output]", "3345\n", () -> capture(StudyCheck::o68));
        check("u1-out-cursor [output]", "Hi, Kai!\nBye\n", () -> capture(StudyCheck::o69));
        check("u1-out-space-tf [output]", "ab", () -> capture(StudyCheck::o70));
        check("u1-str-sub1 [call]", "String:od Mo", () -> e71());
        check("u1-str-sub2 [call]", "String:Morning", () -> e72());
        check("u1-str-sub3 [call]", "String:", () -> e73());
        check("u1-str-sub4 [call]", "throws", () -> e74());
        check("u1-str-len [call]", "int:8", () -> e75());
        check("u1-str-idx1 [call]", "int:2", () -> e76());
        check("u1-str-idx2 [call]", "int:5", () -> e77());
        check("u1-str-idx3 [call]", "int:-1", () -> e78());
        check("u1-str-idx4 [call]", "int:2", () -> e79());
        check("u1-str-cmp1 [cmp]", "4", () -> String.valueOf("Tran".compareTo("Park")));
        check("u1-str-cmp2 [cmp]", "-2", () -> String.valueOf("Park".compareTo("Parker")));
        check("u1-str-cmp3 [cmp]", "32", () -> String.valueOf("apple".compareTo("Apple")));
        check("u1-str-cmp4 [cmp]", "0", () -> String.valueOf("Lee".compareTo("Lee")));
        check("u1-str-explain [call]", "String:an", () -> e84());
        check("u1-str-repair [output]", "Ada", () -> capture(StudyCheck::o85));
        check("u1-str-repair [output]", "da", () -> capture(StudyCheck::o86));
        check("u1-str-repair [output]", "Ad", () -> capture(StudyCheck::o87));
        check("u1-str-repair [output]", " Lovelace", () -> capture(StudyCheck::o88));
        check("u1-str-flip [output]", "Wei, Lin\n", () -> capture(StudyCheck::o89));
        check("u1-str-cmp-tf2 [cmp]", "25", () -> String.valueOf("zoo".compareTo("apple")));
        check("u1-met-max [range]", "3..10", () -> r98(0.0) + ".." + r98(Math.nextDown(1.0)));
        check("u1-met-min [range]", "10..15", () -> r99(0.0) + ".." + r99(Math.nextDown(1.0)));
        check("u1-met-formula [range]", "20..30", () -> r100(0.0) + ".." + r100(Math.nextDown(1.0)));
        check("u1-met-formula [range]", "20..29", () -> r101(0.0) + ".." + r101(Math.nextDown(1.0)));
        check("u1-met-formula [range]", "20..20", () -> r102(0.0) + ".." + r102(Math.nextDown(1.0)));
        check("u1-met-formula [range]", "20..49", () -> r103(0.0) + ".." + r103(Math.nextDown(1.0)));
        check("u1-met-die [range]", "1..1", () -> r104(0.0) + ".." + r104(Math.nextDown(1.0)));
        check("u1-met-die [range]", "1..6", () -> r105(0.0) + ".." + r105(Math.nextDown(1.0)));
        check("u1-met-pow [expr]", "double:9.0", () -> e116());
        check("u1-met-abs [expr]", "int:3", () -> e117());
        check("u1-met-sqrt [expr]", "double:6.0", () -> e118());
        check("u1-obj-alias [output]", "15\n", () -> capture(StudyCheck::o119));
        check("u1-obj-two [output]", "10 15\n", () -> capture(StudyCheck::o120));
        check("u1-obj-reassign [output]", "Bo 11\n", () -> capture(StudyCheck::o121));
        check("u1-obj-null [throws]", "NullPointerException", () -> thrown(StudyCheck::o122));
        check("u1-obj-equals [output]", "true false\n", () -> capture(StudyCheck::o123));
        check("u1-obj-swapref [output]", "10 10 5\n", () -> capture(StudyCheck::o124));
        check("u1-obj-nullafter [output]", "10\n", () -> capture(StudyCheck::o125));
        check("u1-obj-immutable-tf [output]", "hello\n", () -> capture(StudyCheck::o126));
        check("u1-obj-store [output]", "ello\n", () -> capture(StudyCheck::o127));
        JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
        if (javac == null) throw new IllegalStateException("A JDK (not just a JRE) is needed to check compile claims.");
        compileCheck(javac, "u1-run-crash [expr]", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static class Player {     private String name;     private int score;     public Player(String startName, int startScore) { name = startName; score = startScore; }     public String getName() { return name; }     public int getScore() { return score; }     public void addScore(int amount) { score += amount; } } static double area(double width, int sides) { return width * sides; } static int roll(int sides) { return (int) (Math.random() * sides) + 1; } static String run() { int x = 5 / 0.0; return typed(x); } }", "Snip", false);
        compileCheck(javac, "u1-run-ident [ident]", "public class Snip { void f() { int score2 = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-ident [ident]", "public class Snip { void f() { int 2ndPlace = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-ident [ident]", "public class Snip { void f() { int first-name = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-ident [ident]", "public class Snip { void f() { int my score = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-ident [ident]", "public class Snip { void f() { int class = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-ident2 [ident]", "public class Snip { void f() { int total! = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-ident2 [ident]", "public class Snip { void f() { int _count = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-ident2 [ident]", "public class Snip { void f() { int $price = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-ident2 [ident]", "public class Snip { void f() { int numberOfStudents = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-ident2 [ident]", "public class Snip { void f() { int x2 = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-naming [ident]", "public class Snip { void f() { int LibraryBook = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-naming [ident]", "public class Snip { void f() { int libraryBook = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-naming [ident]", "public class Snip { void f() { int LIBRARY_BOOK = 0; } }", "Snip", true);
        compileCheck(javac, "u1-run-naming [ident]", "public class Snip { void f() { int Library-Book = 0; } }", "Snip", false);
        compileCheck(javac, "u1-run-case [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint score = 1;\nint Score = 2;\n}\n}", "Snip", true);
        compileCheck(javac, "u1-run-comment [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\n# total points\nint a = 1;\n}\n}", "Snip", false);
        compileCheck(javac, "u1-run-comment [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\n// total points\nint a = 1;\n}\n}", "Snip", true);
        compileCheck(javac, "u1-run-comment [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\n/* total points */\nint a = 1;\n}\n}", "Snip", true);
        compileCheck(javac, "u1-run-comment [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\n/** total points */\nint a = 1;\n}\n}", "Snip", true);
        compileCheck(javac, "u1-run-fix [compilesClass]", "public class Greeting {\n    public static void main(String[] args) {\n        System.out.println(\"Hi there\");\n    }\n}", "Greeting", true);
        compileCheck(javac, "u1-run-fix [compilesClass]", "public class Greeting {\n    public static void main(String[] args) {\n        System.out.print(\"Hi there\")\n    }\n}", "Greeting", false);
        compileCheck(javac, "u1-run-fix [compilesClass]", "public class Greeting {\n    public static void main(String[] args) {\n        System.out.println('Hi there');\n    }\n}", "Greeting", false);
        compileCheck(javac, "u1-run-fix [compilesClass]", "public class Greeting {\n    public void main(String[] args) {\n        System.out.println(\"Hi there\")\n    }\n}", "Greeting", false);
        compileCheck(javac, "u1-num-lossy [expr]", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static class Player {     private String name;     private int score;     public Player(String startName, int startScore) { name = startName; score = startScore; }     public String getName() { return name; }     public int getScore() { return score; }     public void addScore(int amount) { score += amount; } } static double area(double width, int sides) { return width * sides; } static int roll(int sides) { return (int) (Math.random() * sides) + 1; } static String run() { int n = 90 / 4.0; return typed(n); } }", "Snip", false);
        compileCheck(javac, "u1-num-repair [expr]", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static class Player {     private String name;     private int score;     public Player(String startName, int startScore) { name = startName; score = startScore; }     public String getName() { return name; }     public int getScore() { return score; }     public void addScore(int amount) { score += amount; } } static double area(double width, int sides) { return width * sides; } static int roll(int sides) { return (int) (Math.random() * sides) + 1; } static String run() { int sum = 17; int count = 4; int avg = sum / (double) count; return typed(avg); } }", "Snip", false);
        compileCheck(javac, "u1-out-quote [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nSystem.out.println(\"He said \"go\"\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-out-quote [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nSystem.out.println('He said \"go\"');\n}\n}", "Snip", false);
        compileCheck(javac, "u1-str-type1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint i = \"hello\".indexOf(\"l\");\n}\n}", "Snip", true);
        compileCheck(javac, "u1-str-type1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nString t = \"hello\".indexOf(\"l\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-str-type1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nboolean b = \"hello\".indexOf(\"l\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-str-type1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nchar c = \"hello\".indexOf(\"l\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-str-type2 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nboolean e = \"a\".equals(\"b\");\n}\n}", "Snip", true);
        compileCheck(javac, "u1-str-type2 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint e = \"a\".equals(\"b\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-str-type2 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nString e = \"a\".equals(\"b\");\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-sig1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\ndouble a = area(2.5, 4);\n}\n}", "Snip", true);
        compileCheck(javac, "u1-met-sig1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\ndouble a = area(4, 2.5);\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-sig1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint a = area(2.5, 4);\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-sig1 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\ndouble a = area(2.5);\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-sig2 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\ndouble v = roll(6) + 0.5;\n}\n}", "Snip", true);
        compileCheck(javac, "u1-met-sig2 [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint v = roll(6) + 0.5;\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-math [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint a = Math.abs(-4);\n}\n}", "Snip", true);
        compileCheck(javac, "u1-met-math [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint a = Math.sqrt(16);\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-math [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint a = Math.pow(2, 3);\n}\n}", "Snip", false);
        compileCheck(javac, "u1-met-math [compiles]", "public class Snip {\nstatic String typed(int v) { return \"int:\" + v; }\nstatic String typed(double v) { return \"double:\" + v; }\nstatic String typed(String v) { return \"String:\" + v; }\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic double area(double width, int sides) { return width * sides; }\nstatic int roll(int sides) { return (int) (Math.random() * sides) + 1; }\nstatic void run() {\nint a = Math.random();\n}\n}", "Snip", false);
        System.out.println(failed == 0
            ? "PASS: " + passed + " study specs match Java " + System.getProperty("java.version")
            : failed + " of " + (passed + failed) + " study specs differ");
    }
}
