// Generated by make-java-check.mjs from compareto-cases.json. Do not edit by hand.
public class CompareToCheck {
    static final String[][] CASES = {
        {"apple", "chocolate", "-2"},
        {"banana", "bbnana", "-1"},
        {"cat", "car", "2"},
        {"Roberts", "Roberts", "0"},
        {"applepie", "apple", "3"},
        {"Robe", "Roberts", "-3"},
        {"pie", "applepie", "15"},
        {"Zebra", "apple", "-7"},
        {"Apple", "apple", "-32"},
        {"10", "9", "-8"},
        {"", "a", "-1"},
        {"a", "", "1"},
        {"", "", "0"},
        {"hot dog", "hotdog", "-68"},
        {" cat", "cat", "-67"},
        {"Mister", "Roberts", "-5"},
        {"Roberts", "Mister", "5"},
        {"Roberts", "Robe", "3"},
        {"dog", "dot", "-13"},
        {"stars", "star", "1"},
        {"car", "cartoon", "-4"},
        {"tree", "tree", "0"},
        {"Java", "java", "-32"},
        {"2", "100", "1"},
        {"zoo", "apple", "25"},
        {"bat", "Bat", "32"},
        {"sun", "sunny", "-2"},
        {"a!", "a?", "-30"},
        {"\"hi\"", "hi", "-70"},
        {"tab\there", "tab here", "-23"},
        {"line\nbreak", "line break", "-22"},
        {"caf\u00e9", "cafe", "132"},
        {"back\\slash", "back/slash", "45"},
    };

    public static void main(String[] args) {
        int failures = 0;
        for (String[] c : CASES) {
            int expected = Integer.parseInt(c[2]);
            int actual = c[0].compareTo(c[1]);
            if (actual != expected) {
                failures++;
                System.out.println("FAIL " + show(c[0]) + ".compareTo(" + show(c[1]) + ") = " + actual + ", table says " + expected);
            }
        }
        System.out.println(failures == 0
            ? "PASS: " + CASES.length + " cases match Java " + System.getProperty("java.version")
            : failures + " of " + CASES.length + " cases differ");
    }

    static String show(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (char ch : s.toCharArray()) {
            if (ch >= 32 && ch <= 126) sb.append(ch);
            else sb.append(String.format("\\u%04x", (int) ch));
        }
        return sb.append('"').toString();
    }
}
