// Generated by make-expr-java.mjs from expr-cases.json. Do not edit by hand.
import java.net.URI;
import java.nio.file.Files;
import java.util.List;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

public class ExprCheck {
    static String typed(int v) { return "int:" + v; } static String typed(double v) { return "double:" + v; } static String typed(String v) { return "String:" + v; }

    static String c0() { double z = 5 / 10; return typed(z); }
    static String c1() { int x = 50; int y = 20; int z = 6; return typed(x / y / z); }
    static String c2() { return typed((double) 7 / 2); }
    static String c3() { return typed((double) (7 / 2)); }
    static String c4() { return typed((int) 3.99); }
    static String c5() { return typed(-7 / 2); }
    static String c6() { return typed(-7 % 3); }
    static String c7() { return typed(1 + 2 + "x"); }
    static String c8() { return typed("x" + 1 + 2); }
    static String c9() { int totsec = 3665; return typed(totsec % 3600 / 60); }
    static String c10() { return typed(Math.pow(2, 3)); }
    static String c11() { return typed(Integer.MAX_VALUE + 1); }
    static String c12() { return typed(10 / 4 * 4); }
    static String c13() { return typed(1 / 0); }
    static String c14() { double avg = (90 + 85 + 81) / 3; return typed(avg); }
    static String c15() { return typed((90 + 85 + 81) / 3.0); }
    static String c16() { int n = (int) 9.99; return typed(n); }
    static String c17() { return typed(11 % 4); }
    static String c18() { return typed(-11 / 4); }
    static String c19() { return typed("Total: " + 3 + 4); }
    static String c20() { return typed(3 + 4 + " total"); }
    static String c21() { return typed(100 / 7 * 7); }
    static String c22() { return typed(Math.abs(-4) + 0.5); }
    static String c23() { return typed((double) 1 / 3); }
    static String c24() { int a = 90; int b = 85; int c = 81; double avg = (a + b + c) / 3; return typed(avg); }
    static String c25() { int a = 90; int b = 85; int c = 81; double avg = (a + b + c) / 3.0; return typed(avg); }
    static String c26() { int sum = 7; int n = 2; return typed((double) sum / n); }
    static String c27() { int totsec = 3665; return typed(totsec / 3600 + ":" + totsec % 3600 / 60 + ":" + totsec % 60); }
    static String c28() { return typed("Sum: " + 2 + 3); }
    static String c29() { return typed("Sum: " + (2 + 3)); }
    static String c30() { return typed(Integer.MAX_VALUE * 2); }
    static String c31() { return typed(0.1 + 0.2); }
    static String c32() { return typed(1.0 / 0); }
    static String c33() { return typed(-1.0 / 0); }
    static String c34() { return typed(0.0 / 0); }
    static String c35() { return typed(1e7 * 1.0); }
    static String c36() { return typed(9999999.0 + 0); }
    static String c37() { return typed(0.001 * 1); }
    static String c38() { return typed(0.0001 * 1); }
    static String c39() { return typed(-0.0 * 1); }
    static String c40() { return typed(123456789.0 * 1); }
    static String c41() { return typed((int) 1e10); }
    static String c42() { return typed((int) -2.5); }
    static String c43() { return typed((int) -1e10); }
    static String c44() { return typed(Math.abs(Integer.MIN_VALUE)); }
    static String c45() { return typed(-Integer.MIN_VALUE); }
    static String c46() { return typed(Math.sqrt(-1)); }
    static String c47() { return typed(Math.sqrt(16)); }
    static String c48() { return typed(5 % 0.0); }
    static String c49() { return typed(7 % 2.5); }
    static String c50() { return typed("a" + 1.0); }
    static String c51() { return typed("a" + 1.5e-5); }
    static String c52() { return typed("" + (1 + 2)); }
    static String c53() { return typed("a" + 7 / 2); }
    static String c54() { return typed("a" + 7.0 / 2); }
    static String c55() { return typed(-2147483648); }
    static String c56() { return typed(3 * -2); }
    static String c57() { return typed(46341 * 46341); }
    static String c58() { return typed(5 % -3); }
    static String c59() { return typed(Integer.MIN_VALUE / -1); }
    static String c60() { return typed(7 % 0); }
    static String c61() { int k = 0; return typed(10 / k); }
    static String c62() { double d = 7; return typed(d / 2); }
    static String c63() { double big = Integer.MAX_VALUE + 1; return typed(big); }
    static String c64() { return typed(1.0 * Integer.MAX_VALUE + 1); }

    // {declarations, statement, expected}
    static final String[][] VALID = {
        {"", "double z = 5 / 10;", "double:0.0"},
        {"int x = 50; int y = 20; int z = 6;", "x / y / z", "int:0"},
        {"", "(double) 7 / 2", "double:3.5"},
        {"", "(double) (7 / 2)", "double:3.0"},
        {"", "(int) 3.99", "int:3"},
        {"", "-7 / 2", "int:-3"},
        {"", "-7 % 3", "int:-1"},
        {"", "1 + 2 + \"x\"", "String:3x"},
        {"", "\"x\" + 1 + 2", "String:x12"},
        {"int totsec = 3665;", "totsec % 3600 / 60", "int:1"},
        {"", "Math.pow(2, 3)", "double:8.0"},
        {"", "Integer.MAX_VALUE + 1", "int:-2147483648"},
        {"", "10 / 4 * 4", "int:8"},
        {"", "1 / 0", "throws:ArithmeticException"},
        {"", "double avg = (90 + 85 + 81) / 3;", "double:85.0"},
        {"", "(90 + 85 + 81) / 3.0", "double:85.33333333333333"},
        {"", "int n = (int) 9.99;", "int:9"},
        {"", "11 % 4", "int:3"},
        {"", "-11 / 4", "int:-2"},
        {"", "\"Total: \" + 3 + 4", "String:Total: 34"},
        {"", "3 + 4 + \" total\"", "String:7 total"},
        {"", "100 / 7 * 7", "int:98"},
        {"", "Math.abs(-4) + 0.5", "double:4.5"},
        {"", "(double) 1 / 3", "double:0.3333333333333333"},
        {"int a = 90; int b = 85; int c = 81;", "double avg = (a + b + c) / 3;", "double:85.0"},
        {"int a = 90; int b = 85; int c = 81;", "double avg = (a + b + c) / 3.0;", "double:85.33333333333333"},
        {"int sum = 7; int n = 2;", "(double) sum / n", "double:3.5"},
        {"int totsec = 3665;", "totsec / 3600 + \":\" + totsec % 3600 / 60 + \":\" + totsec % 60", "String:1:1:5"},
        {"", "\"Sum: \" + 2 + 3", "String:Sum: 23"},
        {"", "\"Sum: \" + (2 + 3)", "String:Sum: 5"},
        {"", "Integer.MAX_VALUE * 2", "int:-2"},
        {"", "0.1 + 0.2", "double:0.30000000000000004"},
        {"", "1.0 / 0", "double:Infinity"},
        {"", "-1.0 / 0", "double:-Infinity"},
        {"", "0.0 / 0", "double:NaN"},
        {"", "1e7 * 1.0", "double:1.0E7"},
        {"", "9999999.0 + 0", "double:9999999.0"},
        {"", "0.001 * 1", "double:0.001"},
        {"", "0.0001 * 1", "double:1.0E-4"},
        {"", "-0.0 * 1", "double:-0.0"},
        {"", "123456789.0 * 1", "double:1.23456789E8"},
        {"", "(int) 1e10", "int:2147483647"},
        {"", "(int) -2.5", "int:-2"},
        {"", "(int) -1e10", "int:-2147483648"},
        {"", "Math.abs(Integer.MIN_VALUE)", "int:-2147483648"},
        {"", "-Integer.MIN_VALUE", "int:-2147483648"},
        {"", "Math.sqrt(-1)", "double:NaN"},
        {"", "Math.sqrt(16)", "double:4.0"},
        {"", "5 % 0.0", "double:NaN"},
        {"", "7 % 2.5", "double:2.0"},
        {"", "\"a\" + 1.0", "String:a1.0"},
        {"", "\"a\" + 1.5e-5", "String:a1.5E-5"},
        {"", "\"\" + (1 + 2)", "String:3"},
        {"", "\"a\" + 7 / 2", "String:a3"},
        {"", "\"a\" + 7.0 / 2", "String:a3.5"},
        {"", "-2147483648", "int:-2147483648"},
        {"", "3 * -2", "int:-6"},
        {"", "46341 * 46341", "int:-2147479015"},
        {"", "5 % -3", "int:2"},
        {"", "Integer.MIN_VALUE / -1", "int:-2147483648"},
        {"", "7 % 0", "throws:ArithmeticException"},
        {"int k = 0;", "10 / k", "throws:ArithmeticException"},
        {"double d = 7;", "d / 2", "double:3.5"},
        {"", "double big = Integer.MAX_VALUE + 1;", "double:-2.147483648E9"},
        {"", "1.0 * Integer.MAX_VALUE + 1", "double:2.147483648E9"},
    };
    // {declarations, statement, source that javac must reject}
    static final String[][] REJECT = {
        {"", "int z = 50 / 10.00;", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { int z = 50 / 10.00; return typed(z); } }"},
        {"", "int w = 7.0 / 2;", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { int w = 7.0 / 2; return typed(w); } }"},
        {"String s = \"7\";", "s * 2", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { String s = \"7\"; return typed(s * 2); } }"},
        {"", "int half = 7 / 2.0;", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { int half = 7 / 2.0; return typed(half); } }"},
        {"", "2147483648", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { return typed(2147483648); } }"},
        {"", "String s = 5;", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { String s = 5; return typed(s); } }"},
        {"", "int q = \"5\";", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { int q = \"5\"; return typed(q); } }"},
        {"", "\"a\" - 1", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { return typed(\"a\" - 1); } }"},
        {"", "(int) \"5\"", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { return typed((int) \"5\"); } }"},
        {"", "x + 1", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { return typed(x + 1); } }"},
        {"", "Math.pow(2)", "public class Snip { static String typed(int v) { return \"int:\" + v; } static String typed(double v) { return \"double:\" + v; } static String typed(String v) { return \"String:\" + v; } static String run() { return typed(Math.pow(2)); } }"},
    };

    static String run(int i) {
        switch (i) {
            case 0: return c0();
            case 1: return c1();
            case 2: return c2();
            case 3: return c3();
            case 4: return c4();
            case 5: return c5();
            case 6: return c6();
            case 7: return c7();
            case 8: return c8();
            case 9: return c9();
            case 10: return c10();
            case 11: return c11();
            case 12: return c12();
            case 13: return c13();
            case 14: return c14();
            case 15: return c15();
            case 16: return c16();
            case 17: return c17();
            case 18: return c18();
            case 19: return c19();
            case 20: return c20();
            case 21: return c21();
            case 22: return c22();
            case 23: return c23();
            case 24: return c24();
            case 25: return c25();
            case 26: return c26();
            case 27: return c27();
            case 28: return c28();
            case 29: return c29();
            case 30: return c30();
            case 31: return c31();
            case 32: return c32();
            case 33: return c33();
            case 34: return c34();
            case 35: return c35();
            case 36: return c36();
            case 37: return c37();
            case 38: return c38();
            case 39: return c39();
            case 40: return c40();
            case 41: return c41();
            case 42: return c42();
            case 43: return c43();
            case 44: return c44();
            case 45: return c45();
            case 46: return c46();
            case 47: return c47();
            case 48: return c48();
            case 49: return c49();
            case 50: return c50();
            case 51: return c51();
            case 52: return c52();
            case 53: return c53();
            case 54: return c54();
            case 55: return c55();
            case 56: return c56();
            case 57: return c57();
            case 58: return c58();
            case 59: return c59();
            case 60: return c60();
            case 61: return c61();
            case 62: return c62();
            case 63: return c63();
            case 64: return c64();
            default: throw new IllegalArgumentException();
        }
    }

    public static void main(String[] args) throws Exception {
        int failures = 0;
        for (int i = 0; i < VALID.length; i++) {
            String got;
            try { got = run(i); } catch (ArithmeticException e) { got = "throws:ArithmeticException"; }
            if (!got.equals(VALID[i][2])) {
                failures++;
                System.out.println("FAIL [" + VALID[i][0] + "] " + VALID[i][1] + ": Java gives " + got + ", table says " + VALID[i][2]);
            }
        }
        JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
        if (javac == null) throw new IllegalStateException("A JDK (not just a JRE) is needed to check compile errors.");
        for (String[] c : REJECT) {
            if (compiles(javac, c[2])) {
                failures++;
                System.out.println("FAIL [" + c[0] + "] " + c[1] + ": Java compiles it, but the table says it does not");
            }
        }
        int total = VALID.length + REJECT.length;
        System.out.println(failures == 0
            ? "PASS: " + VALID.length + " results and " + REJECT.length + " compile errors match Java " + System.getProperty("java.version")
            : failures + " of " + total + " cases differ");
    }

    static boolean compiles(JavaCompiler javac, String code) throws Exception {
        JavaFileObject src = new SimpleJavaFileObject(URI.create("string:///Snip.java"), JavaFileObject.Kind.SOURCE) {
            @Override public CharSequence getCharContent(boolean ignoreEncodingErrors) { return code; }
        };
        String out = Files.createTempDirectory("snip").toString();
        return javac.getTask(null, null, new DiagnosticCollector<JavaFileObject>(), List.of("-d", out), null, List.of(src)).call();
    }
}
