// Generated by make-memory-java.mjs from memory-cases.json. Do not edit by hand.
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.net.URI;
import java.nio.file.Files;
import java.util.List;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

public class MemoryCheck {
    static class Player {
        private String name;
        private int score;
        public Player(String startName, int startScore) { name = startName; score = startScore; }
        public String getName() { return name; }
        public int getScore() { return score; }
        public void addScore(int amount) { score += amount; }
    }

    static void m0() {
        Player a = new Player("Ana", 10);
        Player b = a;
        b.addScore(5);
        System.out.println(a.getScore());
    }
    static void m1() {
        Player a = new Player("Ana", 10);
        Player b = new Player("Ana", 10);
        b.addScore(5);
        System.out.println(a.getScore() + " " + b.getScore());
    }
    static void m2() {
        Player a = new Player("Ana", 10);
        Player b = a;
        a = new Player("Bo", 3);
        b.addScore(1);
        System.out.println(a.getName() + " " + b.getScore());
    }
    static void m3() {
        int a = 5;
        int b = a;
        b = b + 1;
        System.out.println(a + " " + b);
    }
    static void m4() {
        String s = new String("hi");
        String t = new String("hi");
        System.out.println(s == t);
        System.out.println(s.equals(t));
    }
    static void m5() {
        String s = "hi";
        String t = "hi";
        System.out.println(s == t);
    }
    static void m6() {
        String w = "hello";
        w.substring(1);
        System.out.println(w);
    }
    static void m7() {
        String w = "hello";
        w = w.substring(1);
        System.out.println(w);
    }
    static void m8() {
        Player a = new Player("Ana", 10);
        Player b = a;
        a = null;
        System.out.println(b.getScore());
    }
    static void m9() {
        Player p = null;
        System.out.println(p.getScore());
    }
    static void m10() {
        Player a = new Player("Ana", 10);
        Player b = new Player("Ana", 10);
        System.out.println(a.equals(b));
    }
    static void m11() {
        Player a = new Player("Ana", 10);
        Player b = new Player("Bo", 4);
        Player c = b;
        b = a;
        c.addScore(1);
        System.out.println(a.getScore() + " " + b.getScore() + " " + c.getScore());
    }
    static void m12() {
        Player x = new Player("Kim", 3);
        Player y = x;
        x.addScore(4);
        y.addScore(1);
        System.out.println(x.getScore());
    }
    static void m13() {
        int a = 7;
        int b = a;
        a = a - 2;
        System.out.println(a + " " + b);
    }
    static void m14() {
        String s = "cat";
        String t = s;
        s = s + "s";
        System.out.println(s + " " + t);
    }
    static void m15() {
        String p = new String("go");
        String q = "go";
        System.out.println(p == q);
        System.out.println(p.equals(q));
    }
    static void m16() {
        Player m = new Player("Max", 2);
        Player n = m;
        n = null;
        System.out.println(m.getScore());
    }
    static void m17() {
        String w = "stone";
        String v = w.substring(1, 4);
        System.out.println(w + " " + v);
    }
    static void m18() {
        Player a = new Player("Ana", 1);
        Player b = a;
        a = new Player("Ana", 1);
        System.out.println(a == b);
        System.out.println(a.getScore() == b.getScore());
    }
    static void m19() {
        String s = null;
        System.out.println(s.length());
    }
    static void m20() {
        String w = "hello";
        w.substring(1);
        w = w.substring(1);
        System.out.println(w);
    }
    static void m21() {
        Player m = new Player("Max", 2);
        Player n = new Player("Max", 2);
        System.out.println(m == n);
        System.out.println(m.getName() == n.getName());
    }
    static void m22() {
        Player a = new Player("Ana", 10);
        Player b = a;
        a = null;
        System.out.println(b.getScore());
        b = null;
    }
    static void m23() {
        String c = "h" + "i";
        System.out.println(c == "hi");
    }
    static void m24() {
        String x = "h";
        String y = x + "i";
        System.out.println(y == "hi");
        System.out.println(y.equals("hi"));
    }
    static void m25() {
        String s = "a" + 1 + 2;
        System.out.println(s == "a12");
    }
    static void m26() {
        String s = "hello";
        String t = s.substring(0);
        System.out.println(s == t);
    }
    static void m27() {
        String s = "hello";
        String t = s.substring(0, 5);
        System.out.println(s == t);
    }
    static void m28() {
        String s = "hello";
        String t = s.substring(1);
        System.out.println(t == "ello");
        System.out.println(t.equals("ello"));
    }
    static void m29() {
        String s = "abc";
        String e = s.substring(1, 1);
        System.out.println(e == "");
    }
    static void m30() {
        Player a = new Player("Ana", 10);
        String n = a.getName();
        System.out.println(n == "Ana");
    }
    static void m31() {
        String s = null;
        System.out.println("a" + s);
    }
    static void m32() {
        String s = "hi";
        System.out.println(s.equals(null));
    }
    static void m33() {
        Player p = new Player("A", 1);
        System.out.println(p.equals(null));
    }
    static void m34() {
        String s = "5";
        System.out.println(s.equals(5));
    }
    static void m35() {
        String s = "abc";
        System.out.println(s.substring(2, 5));
    }
    static void m36() {
        String s = "abc";
        System.out.println(s.indexOf("c") + " " + s.length() + " " + s.compareTo("abd"));
    }
    static void m37() {
        String s = "abc";
        String t = null;
        System.out.println(s.indexOf(t));
    }
    static void m38() {
        int x = 2147483647;
        int y = x + 1;
        System.out.println(y);
    }
    static void m39() {
        boolean same = "a" == "a";
        System.out.println(same);
    }
    static void m40() {
        Player p = new Player(null, 3);
        System.out.println(p.getName());
    }
    static void m41() {
        System.out.print("a");
        System.out.println();
        System.out.print(1 - 3);
    }
    static void m57() {
        Player p = new Player("A", 0);
        System.out.println(p.equals(2));
    }

    static int passed = 0, failed = 0;
    static String capture(Runnable r) {
        PrintStream old = System.out;
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        System.setOut(new PrintStream(buf, true));
        String tail = "";
        try { r.run(); } catch (RuntimeException e) { tail = "|throws:" + e.getClass().getSimpleName(); } finally { System.setOut(old); }
        return buf.toString().replace(System.lineSeparator(), "\n") + tail;
    }
    static void check(String code, String want, Runnable r) {
        String got = capture(r);
        if (got.equals(want)) passed++;
        else { failed++; System.out.println("FAIL " + show(code) + "\n  Java  " + show(got) + "\n  table " + show(want)); }
    }
    static void compileCheck(JavaCompiler javac, String code, String source, boolean shouldCompile) throws Exception {
        JavaFileObject src = new SimpleJavaFileObject(URI.create("string:///Snip.java"), JavaFileObject.Kind.SOURCE) {
            @Override public CharSequence getCharContent(boolean ignore) { return source; }
        };
        String out = Files.createTempDirectory("snip").toString();
        boolean ok = javac.getTask(null, null, new DiagnosticCollector<JavaFileObject>(), List.of("-d", out), null, List.of(src)).call();
        if (ok == shouldCompile) passed++;
        else { failed++; System.out.println("FAIL " + show(code) + ": Java " + (ok ? "compiles" : "rejects") + " it, the table says it " + (shouldCompile ? "is valid Java the tool does not model" : "does not compile")); }
    }
    static String show(String s) { return "\"" + s.replace("\n", "\\n") + "\""; }

    public static void main(String[] args) throws Exception {
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = a;\nb.addScore(5);\nSystem.out.println(a.getScore());", "15\n", MemoryCheck::m0);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = new Player(\"Ana\", 10);\nb.addScore(5);\nSystem.out.println(a.getScore() + \" \" + b.getScore());", "10 15\n", MemoryCheck::m1);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = a;\na = new Player(\"Bo\", 3);\nb.addScore(1);\nSystem.out.println(a.getName() + \" \" + b.getScore());", "Bo 11\n", MemoryCheck::m2);
        check("int a = 5;\nint b = a;\nb = b + 1;\nSystem.out.println(a + \" \" + b);", "5 6\n", MemoryCheck::m3);
        check("String s = new String(\"hi\");\nString t = new String(\"hi\");\nSystem.out.println(s == t);\nSystem.out.println(s.equals(t));", "false\ntrue\n", MemoryCheck::m4);
        check("String s = \"hi\";\nString t = \"hi\";\nSystem.out.println(s == t);", "true\n", MemoryCheck::m5);
        check("String w = \"hello\";\nw.substring(1);\nSystem.out.println(w);", "hello\n", MemoryCheck::m6);
        check("String w = \"hello\";\nw = w.substring(1);\nSystem.out.println(w);", "ello\n", MemoryCheck::m7);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = a;\na = null;\nSystem.out.println(b.getScore());", "10\n", MemoryCheck::m8);
        check("Player p = null;\nSystem.out.println(p.getScore());", "|throws:NullPointerException", MemoryCheck::m9);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = new Player(\"Ana\", 10);\nSystem.out.println(a.equals(b));", "false\n", MemoryCheck::m10);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = new Player(\"Bo\", 4);\nPlayer c = b;\nb = a;\nc.addScore(1);\nSystem.out.println(a.getScore() + \" \" + b.getScore() + \" \" + c.getScore());", "10 10 5\n", MemoryCheck::m11);
        check("Player x = new Player(\"Kim\", 3);\nPlayer y = x;\nx.addScore(4);\ny.addScore(1);\nSystem.out.println(x.getScore());", "8\n", MemoryCheck::m12);
        check("int a = 7;\nint b = a;\na = a - 2;\nSystem.out.println(a + \" \" + b);", "5 7\n", MemoryCheck::m13);
        check("String s = \"cat\";\nString t = s;\ns = s + \"s\";\nSystem.out.println(s + \" \" + t);", "cats cat\n", MemoryCheck::m14);
        check("String p = new String(\"go\");\nString q = \"go\";\nSystem.out.println(p == q);\nSystem.out.println(p.equals(q));", "false\ntrue\n", MemoryCheck::m15);
        check("Player m = new Player(\"Max\", 2);\nPlayer n = m;\nn = null;\nSystem.out.println(m.getScore());", "2\n", MemoryCheck::m16);
        check("String w = \"stone\";\nString v = w.substring(1, 4);\nSystem.out.println(w + \" \" + v);", "stone ton\n", MemoryCheck::m17);
        check("Player a = new Player(\"Ana\", 1);\nPlayer b = a;\na = new Player(\"Ana\", 1);\nSystem.out.println(a == b);\nSystem.out.println(a.getScore() == b.getScore());", "false\ntrue\n", MemoryCheck::m18);
        check("String s = null;\nSystem.out.println(s.length());", "|throws:NullPointerException", MemoryCheck::m19);
        check("String w = \"hello\";\nw.substring(1);\nw = w.substring(1);\nSystem.out.println(w);", "ello\n", MemoryCheck::m20);
        check("Player m = new Player(\"Max\", 2);\nPlayer n = new Player(\"Max\", 2);\nSystem.out.println(m == n);\nSystem.out.println(m.getName() == n.getName());", "false\ntrue\n", MemoryCheck::m21);
        check("Player a = new Player(\"Ana\", 10);\nPlayer b = a;\na = null;\nSystem.out.println(b.getScore());\nb = null;", "10\n", MemoryCheck::m22);
        check("String c = \"h\" + \"i\";\nSystem.out.println(c == \"hi\");", "true\n", MemoryCheck::m23);
        check("String x = \"h\";\nString y = x + \"i\";\nSystem.out.println(y == \"hi\");\nSystem.out.println(y.equals(\"hi\"));", "false\ntrue\n", MemoryCheck::m24);
        check("String s = \"a\" + 1 + 2;\nSystem.out.println(s == \"a12\");", "true\n", MemoryCheck::m25);
        check("String s = \"hello\";\nString t = s.substring(0);\nSystem.out.println(s == t);", "true\n", MemoryCheck::m26);
        check("String s = \"hello\";\nString t = s.substring(0, 5);\nSystem.out.println(s == t);", "true\n", MemoryCheck::m27);
        check("String s = \"hello\";\nString t = s.substring(1);\nSystem.out.println(t == \"ello\");\nSystem.out.println(t.equals(\"ello\"));", "false\ntrue\n", MemoryCheck::m28);
        check("String s = \"abc\";\nString e = s.substring(1, 1);\nSystem.out.println(e == \"\");", "true\n", MemoryCheck::m29);
        check("Player a = new Player(\"Ana\", 10);\nString n = a.getName();\nSystem.out.println(n == \"Ana\");", "true\n", MemoryCheck::m30);
        check("String s = null;\nSystem.out.println(\"a\" + s);", "anull\n", MemoryCheck::m31);
        check("String s = \"hi\";\nSystem.out.println(s.equals(null));", "false\n", MemoryCheck::m32);
        check("Player p = new Player(\"A\", 1);\nSystem.out.println(p.equals(null));", "false\n", MemoryCheck::m33);
        check("String s = \"5\";\nSystem.out.println(s.equals(5));", "false\n", MemoryCheck::m34);
        check("String s = \"abc\";\nSystem.out.println(s.substring(2, 5));", "|throws:StringIndexOutOfBoundsException", MemoryCheck::m35);
        check("String s = \"abc\";\nSystem.out.println(s.indexOf(\"c\") + \" \" + s.length() + \" \" + s.compareTo(\"abd\"));", "2 3 -1\n", MemoryCheck::m36);
        check("String s = \"abc\";\nString t = null;\nSystem.out.println(s.indexOf(t));", "|throws:NullPointerException", MemoryCheck::m37);
        check("int x = 2147483647;\nint y = x + 1;\nSystem.out.println(y);", "-2147483648\n", MemoryCheck::m38);
        check("boolean same = \"a\" == \"a\";\nSystem.out.println(same);", "true\n", MemoryCheck::m39);
        check("Player p = new Player(null, 3);\nSystem.out.println(p.getName());", "null\n", MemoryCheck::m40);
        check("System.out.print(\"a\");\nSystem.out.println();\nSystem.out.print(1 - 3);", "a\n-2", MemoryCheck::m41);
        check("Player p = new Player(\"A\", 0);\nSystem.out.println(p.equals(2));", "false\n", MemoryCheck::m57);
        JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
        if (javac == null) throw new IllegalStateException("A JDK is needed to check compile claims.");
        compileCheck(javac, "Player p = \"Ana\";", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer p = \"Ana\";\n}\n}", false);
        compileCheck(javac, "String s = new Player(\"A\", 1);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nString s = new Player(\"A\", 1);\n}\n}", false);
        compileCheck(javac, "int n = \"5\";", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nint n = \"5\";\n}\n}", false);
        compileCheck(javac, "System.out.println(q);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nSystem.out.println(q);\n}\n}", false);
        compileCheck(javac, "Player a = new Player(\"Ana\", 10);\nString s = \"A\";\nSystem.out.println(a == s);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer a = new Player(\"Ana\", 10);\nString s = \"A\";\nSystem.out.println(a == s);\n}\n}", false);
        compileCheck(javac, "Player a = new Player(\"Ana\", 10);\na.setScore(3);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer a = new Player(\"Ana\", 10);\na.setScore(3);\n}\n}", false);
        compileCheck(javac, "int a = 1;\nint b = 2;\na == b;", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nint a = 1;\nint b = 2;\na == b;\n}\n}", false);
        compileCheck(javac, "Player p = new Player(\"A\");", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer p = new Player(\"A\");\n}\n}", false);
        compileCheck(javac, "int n = 5;\nSystem.out.println(n.length());", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nint n = 5;\nSystem.out.println(n.length());\n}\n}", false);
        compileCheck(javac, "String s = \"a\";\nString s = \"b\";", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nString s = \"a\";\nString s = \"b\";\n}\n}", false);
        compileCheck(javac, "Player p = new Player(\"A\", 1)", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer p = new Player(\"A\", 1)\n}\n}", false);
        compileCheck(javac, "String s = \"a\";\nSystem.out.println(s.toUpperCase());", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nString s = \"a\";\nSystem.out.println(s.toUpperCase());\n}\n}", true);
        compileCheck(javac, "Player a = new Player(\"Ana\", 10);\nSystem.out.println(a);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer a = new Player(\"Ana\", 10);\nSystem.out.println(a);\n}\n}", true);
        compileCheck(javac, "double d = 1.5;\nSystem.out.println(d);", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\ndouble d = 1.5;\nSystem.out.println(d);\n}\n}", true);
        compileCheck(javac, "String s = \"abc\";\nSystem.out.println(s.indexOf(98));", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nString s = \"abc\";\nSystem.out.println(s.indexOf(98));\n}\n}", true);
        compileCheck(javac, "Player p = new Player(\"A\", 0);\nSystem.out.println(p.toString());", "public class Snip {\nstatic class Player {\n    private String name;\n    private int score;\n    public Player(String startName, int startScore) { name = startName; score = startScore; }\n    public String getName() { return name; }\n    public int getScore() { return score; }\n    public void addScore(int amount) { score += amount; }\n}\nstatic void run() {\nPlayer p = new Player(\"A\", 0);\nSystem.out.println(p.toString());\n}\n}", true);
        System.out.println(failed == 0 ? "PASS: " + passed + " programs match Java " + System.getProperty("java.version") : failed + " of " + (passed + failed) + " programs differ");
    }
}
