// Generated by make-output-java.mjs from output-cases.json. Do not edit by hand.
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.net.URI;
import java.nio.file.Files;
import java.util.List;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

public class OutputCheck {
    static void p0() {
        System.out.print("Snow");
        System.out.println("ball " + "fight");
        System.out.println("Game" + "over");
    }
    static void p1() {
        System.out.println("Line one\nLine two\tand a tab");
    }
    static void p2() {
        System.out.print("A");
        System.out.println();
        System.out.print("B");
    }
    static void p3() {
        System.out.println("Total: " + 4 + 5);
    }
    static void p4() {
        System.out.println(4 + 5 + " total");
    }
    static void p5() {
        System.out.println("Say \"hi\" \\ bye");
    }
    static void p6() {
        System.out.println(7 / 2 + " and " + 7 / 2.0);
    }
    static void p7() {
        System.out.println("top");
        System.out.println();
        System.out.println("bottom");
    }
    static void p8() {
        System.out.print("a\n");
        System.out.print("b");
    }
    static void p9() {
        int x = 3;
        String s = "x = ";
        System.out.print(s);
        System.out.println(x + 1);
    }
    static void p10() {
        System.out.print("one ");
        System.out.print("two ");
        System.out.println("three");
        System.out.print("four");
    }
    static void p11() {
        System.out.print("Hot");
        System.out.print("dog");
        System.out.println("!");
    }
    static void p12() {
        System.out.println("a\tb\nc\\d");
    }
    static void p13() {
        System.out.println("Sum: " + (2 + 3));
    }
    static void p14() {
        System.out.println(1 + 2 + "3");
    }
    static void p15() {
        System.out.print("x");
        System.out.println("y");
        System.out.print("z");
    }
    static void p16() {
        System.out.println("\"Quote\"");
    }
    static void p17() {
        System.out.println();
        System.out.println("start");
    }
    static void p18() {
        double d = 2;
        System.out.println(d + " cups");
    }
    static void p19() {
        System.out.println("Line one\nLine two\tand a tab");
        System.out.println("Say \"hi\" \\ bye");
    }
    static void p20() {
        System.out.println("Total: " + 4 + 5);
        System.out.println(4 + 5 + " total");
        System.out.println("Total: " + (4 + 5));
    }
    static void p21() {
        System.out.println(7 / 2 + " and " + 7 / 2.0);
        System.out.println(10.0 / 4);
        System.out.println(1.0 * 3);
    }
    static void p22() {
        System.out.print("a");
        System.out.print("");
        System.out.println("b");
    }
    static void p23() {
        System.out.println("" + 1.0 / 3);
    }
    static void p24() {
        System.out.println(1e7);
    }
    static void p25() {
        String s = "x";
        System.out.println(s + s + 1 + 1);
    }
    static void p26() {
        System.out.println(-7 / 2 + "" + -7 % 2);
    }
    static void p27() {
        System.out.print("no newline at end");
    }
    static void p28() {
        // a comment line is skipped
        System.out.println("ok");
    }
    static void p29() {
        System.out.println("before");
        int x = 1 / 0;
        System.out.println(x);
    }
    static void p30() {
        System.out.print("a");
        System.out.println(5 % 0);
    }

    interface StudyRun { void run(); static StudyRun of(StudyRun r) { return r; } }
    static int passed = 0, failed = 0;

    // Output exactly as printed; a crash adds "|throws:<Exception>" after whatever was printed first.
    static String capture(StudyRun r) {
        PrintStream old = System.out;
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        System.setOut(new PrintStream(buf, true));
        String tail = "";
        try { r.run(); } catch (RuntimeException e) { tail = "|throws:" + e.getClass().getSimpleName(); } finally { System.setOut(old); }
        return buf.toString().replace(System.lineSeparator(), "\n") + tail;
    }
    static void check(String code, String want, StudyRun r) {
        String got = capture(r);
        if (got.equals(want)) passed++;
        else { failed++; System.out.println("FAIL " + show(code) + "\n  Java  " + show(got) + "\n  table " + show(want)); }
    }
    static void reject(JavaCompiler javac, String code, String source) throws Exception {
        JavaFileObject src = new SimpleJavaFileObject(URI.create("string:///Snip.java"), JavaFileObject.Kind.SOURCE) {
            @Override public CharSequence getCharContent(boolean ignore) { return source; }
        };
        String out = Files.createTempDirectory("snip").toString();
        boolean ok = javac.getTask(null, null, new DiagnosticCollector<JavaFileObject>(), List.of("-d", out), null, List.of(src)).call();
        if (!ok) passed++;
        else { failed++; System.out.println("FAIL " + show(code) + ": Java compiles it, but the table says it does not"); }
    }
    static String show(String s) { return "\"" + s.replace("\n", "\\n").replace("\t", "\\t") + "\""; }

    public static void main(String[] args) throws Exception {
        check("System.out.print(\"Snow\");\nSystem.out.println(\"ball \" + \"fight\");\nSystem.out.println(\"Game\" + \"over\");", "Snowball fight\nGameover\n", StudyRun.of(OutputCheck::p0));
        check("System.out.println(\"Line one\\nLine two\\tand a tab\");", "Line one\nLine two\tand a tab\n", StudyRun.of(OutputCheck::p1));
        check("System.out.print(\"A\");\nSystem.out.println();\nSystem.out.print(\"B\");", "A\nB", StudyRun.of(OutputCheck::p2));
        check("System.out.println(\"Total: \" + 4 + 5);", "Total: 45\n", StudyRun.of(OutputCheck::p3));
        check("System.out.println(4 + 5 + \" total\");", "9 total\n", StudyRun.of(OutputCheck::p4));
        check("System.out.println(\"Say \\\"hi\\\" \\\\ bye\");", "Say \"hi\" \\ bye\n", StudyRun.of(OutputCheck::p5));
        check("System.out.println(7 / 2 + \" and \" + 7 / 2.0);", "3 and 3.5\n", StudyRun.of(OutputCheck::p6));
        check("System.out.println(\"top\");\nSystem.out.println();\nSystem.out.println(\"bottom\");", "top\n\nbottom\n", StudyRun.of(OutputCheck::p7));
        check("System.out.print(\"a\\n\");\nSystem.out.print(\"b\");", "a\nb", StudyRun.of(OutputCheck::p8));
        check("int x = 3;\nString s = \"x = \";\nSystem.out.print(s);\nSystem.out.println(x + 1);", "x = 4\n", StudyRun.of(OutputCheck::p9));
        check("System.out.print(\"one \");\nSystem.out.print(\"two \");\nSystem.out.println(\"three\");\nSystem.out.print(\"four\");", "one two three\nfour", StudyRun.of(OutputCheck::p10));
        check("System.out.print(\"Hot\");\nSystem.out.print(\"dog\");\nSystem.out.println(\"!\");", "Hotdog!\n", StudyRun.of(OutputCheck::p11));
        check("System.out.println(\"a\\tb\\nc\\\\d\");", "a\tb\nc\\d\n", StudyRun.of(OutputCheck::p12));
        check("System.out.println(\"Sum: \" + (2 + 3));", "Sum: 5\n", StudyRun.of(OutputCheck::p13));
        check("System.out.println(1 + 2 + \"3\");", "33\n", StudyRun.of(OutputCheck::p14));
        check("System.out.print(\"x\");\nSystem.out.println(\"y\");\nSystem.out.print(\"z\");", "xy\nz", StudyRun.of(OutputCheck::p15));
        check("System.out.println(\"\\\"Quote\\\"\");", "\"Quote\"\n", StudyRun.of(OutputCheck::p16));
        check("System.out.println();\nSystem.out.println(\"start\");", "\nstart\n", StudyRun.of(OutputCheck::p17));
        check("double d = 2;\nSystem.out.println(d + \" cups\");", "2.0 cups\n", StudyRun.of(OutputCheck::p18));
        check("System.out.println(\"Line one\\nLine two\\tand a tab\");\nSystem.out.println(\"Say \\\"hi\\\" \\\\ bye\");", "Line one\nLine two\tand a tab\nSay \"hi\" \\ bye\n", StudyRun.of(OutputCheck::p19));
        check("System.out.println(\"Total: \" + 4 + 5);\nSystem.out.println(4 + 5 + \" total\");\nSystem.out.println(\"Total: \" + (4 + 5));", "Total: 45\n9 total\nTotal: 9\n", StudyRun.of(OutputCheck::p20));
        check("System.out.println(7 / 2 + \" and \" + 7 / 2.0);\nSystem.out.println(10.0 / 4);\nSystem.out.println(1.0 * 3);", "3 and 3.5\n2.5\n3.0\n", StudyRun.of(OutputCheck::p21));
        check("System.out.print(\"a\");\nSystem.out.print(\"\");\nSystem.out.println(\"b\");", "ab\n", StudyRun.of(OutputCheck::p22));
        check("System.out.println(\"\" + 1.0 / 3);", "0.3333333333333333\n", StudyRun.of(OutputCheck::p23));
        check("System.out.println(1e7);", "1.0E7\n", StudyRun.of(OutputCheck::p24));
        check("String s = \"x\";\nSystem.out.println(s + s + 1 + 1);", "xx11\n", StudyRun.of(OutputCheck::p25));
        check("System.out.println(-7 / 2 + \"\" + -7 % 2);", "-3-1\n", StudyRun.of(OutputCheck::p26));
        check("System.out.print(\"no newline at end\");", "no newline at end", StudyRun.of(OutputCheck::p27));
        check("// a comment line is skipped\nSystem.out.println(\"ok\");", "ok\n", StudyRun.of(OutputCheck::p28));
        check("System.out.println(\"before\");\nint x = 1 / 0;\nSystem.out.println(x);", "before\n|throws:ArithmeticException", StudyRun.of(OutputCheck::p29));
        check("System.out.print(\"a\");\nSystem.out.println(5 % 0);", "a|throws:ArithmeticException", StudyRun.of(OutputCheck::p30));
        JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
        if (javac == null) throw new IllegalStateException("A JDK is needed to check compile errors.");
        reject(javac, "System.out.print();", "public class Snip { static void run() {\nSystem.out.print();\n} }");
        reject(javac, "System.out.println(\"x\")", "public class Snip { static void run() {\nSystem.out.println(\"x\")\n} }");
        reject(javac, "System.out.println(\"a\" - 1);", "public class Snip { static void run() {\nSystem.out.println(\"a\" - 1);\n} }");
        reject(javac, "int x = 3.5;\nSystem.out.println(x);", "public class Snip { static void run() {\nint x = 3.5;\nSystem.out.println(x);\n} }");
        reject(javac, "System.out.println(y);", "public class Snip { static void run() {\nSystem.out.println(y);\n} }");
        System.out.println(failed == 0 ? "PASS: " + passed + " programs match Java " + System.getProperty("java.version") : failed + " of " + (passed + failed) + " programs differ");
    }
}
