// Generated by make-range-java.mjs from range-cases.json. Do not edit by hand.
import java.net.URI;
import java.nio.file.Files;
import java.util.List;
import java.util.TreeMap;
import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.ToolProvider;

public class RangeCheck {
    static int f0(double r) { return (int) (r * 6) + 1; }
    static int f1(double r) { return (int) (r * 10) + 5; }
    static int f2(double r) { return (int) (r * 8) + 3; }
    static int f3(double r) { return (int) (r * 8) + 5; }
    static int f4(double r) { return (int) (r * 7) + 5; }
    static int f5(double r) { return (int) r * 8 + 5; }
    static int f6(double r) { return (int) (r * 12) + 5; }
    static int f7(double r) { return (int) r * 100; }
    static int f8(double r) { return (int) (r * 6 + 1); }
    static int f9(double r) { return (int) (r * 11) - 5; }
    static int f10(double r) { return (int) (r * 11 - 5); }
    static int f11(double r) { return (int) (r * (20 - 10 + 1)) + 10; }
    static int f12(double r) { return (int) (r * 4) + 7; }
    static int f13(double r) { return (int) (r * 50); }
    static int f14(double r) { return (int) (r * 100) + 1; }
    static int f15(double r) { return (int) (r * 100); }
    static int f16(double r) { return (int) (r * 101); }
    static int f17(double r) { return (int) (r * 99) + 1; }
    static int f18(double r) { return (int) (r * 3) * 2; }
    static int f19(double r) { return (int) (r * 0.5); }
    static int f20(double r) { return (int) (r * 21) - 10; }
    static int f21(double r) { return (int) (r * 11) + 15; }
    static int f22(double r) { return (int) (r * 10) + 15; }
    static int f23(double r) { return (int) r * 11 + 15; }
    static int f24(double r) { return (int) (r * 11 + 15); }
    static int f25(double r) { return (int) (r * 6) * 1 + 0; }
    static int f26(double r) { return (int) (r * 100000) - 50000; }
    static int f27(double r) { return (int) (r * 1000) + 1; }
    static int f29(double r) { return (int) (r * 6) / 0; }

    interface OutputFn { int apply(double r); static OutputFn of(OutputFn f) { return f; } }
    static final int GRID = 12000;
    static final double[] SAMPLES = { 0.0, Math.nextDown(1.0), 0.0078125, 0.0234375, 0.0390625, 0.0546875, 0.0703125, 0.0859375, 0.1015625, 0.1171875, 0.1328125, 0.1484375, 0.1640625, 0.1796875, 0.1953125, 0.2109375, 0.2265625, 0.2421875, 0.2578125, 0.2734375, 0.2890625, 0.3046875, 0.3203125, 0.3359375, 0.3515625, 0.3671875, 0.3828125, 0.3984375, 0.4140625, 0.4296875, 0.4453125, 0.4609375, 0.4765625, 0.4921875, 0.5078125, 0.5234375, 0.5390625, 0.5546875, 0.5703125, 0.5859375, 0.6015625, 0.6171875, 0.6328125, 0.6484375, 0.6640625, 0.6796875, 0.6953125, 0.7109375, 0.7265625, 0.7421875, 0.7578125, 0.7734375, 0.7890625, 0.8046875, 0.8203125, 0.8359375, 0.8515625, 0.8671875, 0.8828125, 0.8984375, 0.9140625, 0.9296875, 0.9453125, 0.9609375, 0.9765625, 0.9921875 };
    static int passed = 0, failed = 0;

    static void fail(String formula, String what) { failed++; System.out.println("FAIL " + formula + ": " + what); }

    static void analyze(String formula, OutputFn f, int min, int max, int count, Integer mode, String edgeLow, String edgeTop, int[] engine) {
        TreeMap<Integer, Integer> counts = new TreeMap<>();
        for (int i = 0; i < GRID; i++) counts.merge(f.apply((i + 0.5) / GRID), 1, Integer::sum);
        int lo = f.apply(0.0), hi = f.apply(Math.nextDown(1.0));
        TreeMap<Integer, Integer> all = new TreeMap<>(counts);
        all.putIfAbsent(lo, 0); all.putIfAbsent(hi, 0);
        String low = counts.containsKey(lo) ? "" : String.valueOf(lo);
        String top = counts.containsKey(hi) || hi == lo ? "" : String.valueOf(hi);
        Integer best = null; int bestCount = -1; boolean tie = false;
        for (var e : counts.entrySet()) { if (e.getValue() > bestCount) { bestCount = e.getValue(); best = e.getKey(); tie = false; } else if (e.getValue() == bestCount) tie = true; }
        if (tie) best = null;
        String got = all.firstKey() + " " + all.lastKey() + " " + all.size() + " " + best + " [" + low + "] [" + top + "]";
        String want = min + " " + max + " " + count + " " + mode + " [" + edgeLow + "] [" + edgeTop + "]";
        if (!got.equals(want)) fail(formula, "Java gives min max count mode edges = " + got + ", table says " + want);
        for (int s = 0; s < SAMPLES.length; s++)
            if (f.apply(SAMPLES[s]) != engine[s]) fail(formula, "at r = " + SAMPLES[s] + " Java gives " + f.apply(SAMPLES[s]) + ", the page's engine gives " + engine[s]);
        passed++;
    }
    // Formulas with too many values: only the two ends are claimed (the formula rises steadily).
    static void ends(String formula, OutputFn f, int min, int max, int[] engine) {
        int lo = f.apply(0.0), hi = f.apply(Math.nextDown(1.0));
        if (lo != min || hi != max) fail(formula, "Java gives " + lo + " to " + hi + ", table says " + min + " to " + max);
        for (int s = 0; s < SAMPLES.length; s++)
            if (f.apply(SAMPLES[s]) != engine[s]) fail(formula, "at r = " + SAMPLES[s] + " Java gives " + f.apply(SAMPLES[s]) + ", the page's engine gives " + engine[s]);
        passed++;
    }
    static void expectThrows(String formula, String type, Runnable r) {
        try { r.run(); fail(formula, "Java does not throw"); } catch (RuntimeException e) { if (e.getClass().getSimpleName().equals(type)) passed++; else fail(formula, "Java throws " + e.getClass().getSimpleName()); }
    }
    static void expectThrows(String formula, String type, java.util.function.IntSupplier s) { expectThrows(formula, type, (Runnable) () -> s.getAsInt()); }
    static void compileCheck(JavaCompiler javac, String formula, String source, boolean shouldCompile) throws Exception {
        JavaFileObject src = new SimpleJavaFileObject(URI.create("string:///Snip.java"), JavaFileObject.Kind.SOURCE) {
            @Override public CharSequence getCharContent(boolean ignore) { return source; }
        };
        String out = Files.createTempDirectory("snip").toString();
        if (javac.getTask(null, null, new DiagnosticCollector<JavaFileObject>(), List.of("-d", out), null, List.of(src)).call() == shouldCompile) passed++;
        else fail(formula, "Java " + (shouldCompile ? "rejects a valid formula" : "compiles an invalid formula"));
    }

    public static void main(String[] args) throws Exception {
        analyze("(int) (Math.random() * 6) + 1", OutputFn.of(RangeCheck::f0), 1, 6, 6, null, "", "", new int[] {1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6});
        analyze("(int) (Math.random() * 10) + 5", OutputFn.of(RangeCheck::f1), 5, 14, 10, null, "", "", new int[] {5, 14, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14});
        analyze("(int) (Math.random() * 8) + 3", OutputFn.of(RangeCheck::f2), 3, 10, 8, null, "", "", new int[] {3, 10, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10});
        analyze("(int) (Math.random() * 8) + 5", OutputFn.of(RangeCheck::f3), 5, 12, 8, null, "", "", new int[] {5, 12, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12});
        analyze("(int) (Math.random() * 7) + 5", OutputFn.of(RangeCheck::f4), 5, 11, 7, null, "", "", new int[] {5, 11, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11});
        analyze("(int) Math.random() * 8 + 5", OutputFn.of(RangeCheck::f5), 5, 5, 1, 5, "", "", new int[] {5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5});
        analyze("(int) (Math.random() * 12) + 5", OutputFn.of(RangeCheck::f6), 5, 16, 12, null, "", "", new int[] {5, 16, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16});
        analyze("(int) Math.random() * 100", OutputFn.of(RangeCheck::f7), 0, 0, 1, 0, "", "", new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        analyze("(int) (Math.random() * 6 + 1)", OutputFn.of(RangeCheck::f8), 1, 6, 6, null, "", "", new int[] {1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6});
        analyze("(int) (Math.random() * 11) - 5", OutputFn.of(RangeCheck::f9), -5, 5, 11, null, "", "", new int[] {-5, 5, -5, -5, -5, -5, -5, -5, -4, -4, -4, -4, -4, -4, -3, -3, -3, -3, -3, -2, -2, -2, -2, -2, -2, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5});
        analyze("(int) (Math.random() * 11 - 5)", OutputFn.of(RangeCheck::f10), -5, 5, 11, 0, "-5", "", new int[] {-5, 5, -4, -4, -4, -4, -4, -4, -3, -3, -3, -3, -3, -3, -2, -2, -2, -2, -2, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5});
        analyze("(int) (Math.random() * (20 - 10 + 1)) + 10", OutputFn.of(RangeCheck::f11), 10, 20, 11, null, "", "", new int[] {10, 20, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20});
        analyze("(int) (Math.random() * 4) + 7", OutputFn.of(RangeCheck::f12), 7, 10, 4, null, "", "", new int[] {7, 10, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10});
        analyze("(int) (Math.random() * 50)", OutputFn.of(RangeCheck::f13), 0, 49, 50, null, "", "", new int[] {0, 49, 0, 1, 1, 2, 3, 4, 5, 5, 6, 7, 8, 8, 9, 10, 11, 12, 12, 13, 14, 15, 16, 16, 17, 18, 19, 19, 20, 21, 22, 23, 23, 24, 25, 26, 26, 27, 28, 29, 30, 30, 31, 32, 33, 33, 34, 35, 36, 37, 37, 38, 39, 40, 41, 41, 42, 43, 44, 44, 45, 46, 47, 48, 48, 49});
        analyze("(int) (Math.random() * 100) + 1", OutputFn.of(RangeCheck::f14), 1, 100, 100, null, "", "", new int[] {1, 100, 1, 3, 4, 6, 8, 9, 11, 12, 14, 15, 17, 18, 20, 22, 23, 25, 26, 28, 29, 31, 33, 34, 36, 37, 39, 40, 42, 43, 45, 47, 48, 50, 51, 53, 54, 56, 58, 59, 61, 62, 64, 65, 67, 68, 70, 72, 73, 75, 76, 78, 79, 81, 83, 84, 86, 87, 89, 90, 92, 93, 95, 97, 98, 100});
        analyze("(int) (Math.random() * 100)", OutputFn.of(RangeCheck::f15), 0, 99, 100, null, "", "", new int[] {0, 99, 0, 2, 3, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 21, 22, 24, 25, 27, 28, 30, 32, 33, 35, 36, 38, 39, 41, 42, 44, 46, 47, 49, 50, 52, 53, 55, 57, 58, 60, 61, 63, 64, 66, 67, 69, 71, 72, 74, 75, 77, 78, 80, 82, 83, 85, 86, 88, 89, 91, 92, 94, 96, 97, 99});
        analyze("(int) (Math.random() * 101)", OutputFn.of(RangeCheck::f16), 0, 100, 101, null, "", "", new int[] {0, 100, 0, 2, 3, 5, 7, 8, 10, 11, 13, 14, 16, 18, 19, 21, 22, 24, 26, 27, 29, 30, 32, 33, 35, 37, 38, 40, 41, 43, 44, 46, 48, 49, 51, 52, 54, 56, 57, 59, 60, 62, 63, 65, 67, 68, 70, 71, 73, 74, 76, 78, 79, 81, 82, 84, 86, 87, 89, 90, 92, 93, 95, 97, 98, 100});
        analyze("(int) (Math.random() * 99) + 1", OutputFn.of(RangeCheck::f17), 1, 99, 99, null, "", "", new int[] {1, 99, 1, 3, 4, 6, 7, 9, 11, 12, 14, 15, 17, 18, 20, 21, 23, 24, 26, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 43, 45, 46, 48, 49, 51, 52, 54, 55, 57, 59, 60, 62, 63, 65, 66, 68, 69, 71, 72, 74, 76, 77, 79, 80, 82, 83, 85, 86, 88, 89, 91, 93, 94, 96, 97, 99});
        analyze("(int) (Math.random() * 3) * 2", OutputFn.of(RangeCheck::f18), 0, 4, 3, null, "", "", new int[] {0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4});
        analyze("(int) (Math.random() * 0.5)", OutputFn.of(RangeCheck::f19), 0, 0, 1, 0, "", "", new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0});
        analyze("(int) (Math.random() * 21) - 10", OutputFn.of(RangeCheck::f20), -10, 10, 21, null, "", "", new int[] {-10, 10, -10, -10, -10, -9, -9, -9, -8, -8, -8, -7, -7, -7, -6, -6, -6, -5, -5, -5, -4, -4, -4, -3, -3, -3, -2, -2, -2, -1, -1, -1, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10, 10, 10});
        analyze("(int) (Math.random() * 11) + 15", OutputFn.of(RangeCheck::f21), 15, 25, 11, null, "", "", new int[] {15, 25, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25});
        analyze("(int) (Math.random() * 10) + 15", OutputFn.of(RangeCheck::f22), 15, 24, 10, null, "", "", new int[] {15, 24, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24});
        analyze("(int) Math.random() * 11 + 15", OutputFn.of(RangeCheck::f23), 15, 15, 1, 15, "", "", new int[] {15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15});
        analyze("(int) (Math.random() * 11 + 15)", OutputFn.of(RangeCheck::f24), 15, 26, 12, null, "", "26", new int[] {15, 26, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25});
        analyze("(int) (Math.random() * 6) * 1 + 0", OutputFn.of(RangeCheck::f25), 0, 5, 6, null, "", "", new int[] {0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5});
        ends("(int) (Math.random() * 100000) - 50000", OutputFn.of(RangeCheck::f26), -50000, 49999, new int[] {-50000, 49999, -49219, -47657, -46094, -44532, -42969, -41407, -39844, -38282, -36719, -35157, -33594, -32032, -30469, -28907, -27344, -25782, -24219, -22657, -21094, -19532, -17969, -16407, -14844, -13282, -11719, -10157, -8594, -7032, -5469, -3907, -2344, -782, 781, 2343, 3906, 5468, 7031, 8593, 10156, 11718, 13281, 14843, 16406, 17968, 19531, 21093, 22656, 24218, 25781, 27343, 28906, 30468, 32031, 33593, 35156, 36718, 38281, 39843, 41406, 42968, 44531, 46093, 47656, 49218});
        analyze("(int) (Math.random() * 1000) + 1", OutputFn.of(RangeCheck::f27), 1, 1000, 1000, null, "", "", new int[] {1, 1000, 8, 24, 40, 55, 71, 86, 102, 118, 133, 149, 165, 180, 196, 211, 227, 243, 258, 274, 290, 305, 321, 336, 352, 368, 383, 399, 415, 430, 446, 461, 477, 493, 508, 524, 540, 555, 571, 586, 602, 618, 633, 649, 665, 680, 696, 711, 727, 743, 758, 774, 790, 805, 821, 836, 852, 868, 883, 899, 915, 930, 946, 961, 977, 993});
        expectThrows("(int) (Math.random() * 6) / 0", "ArithmeticException", () -> f29(0.5));
        JavaCompiler javac = ToolProvider.getSystemJavaCompiler();
        if (javac == null) throw new IllegalStateException("A JDK is needed to check compile errors.");
        compileCheck(javac, "(int) (Math.random() * 6) + ", "public class Snip { static int f(double r) { return (int) (r * 6) +; } }", false);
        compileCheck(javac, "(int) ((Math.random() - Math.random()) * 10)", "public class Snip { static int f() { return (int) ((Math.random() - Math.random()) * 10); } }", true);
        compileCheck(javac, "(int) (1 / (Math.random() - 0.5))", "public class Snip { static int f() { return (int) (1 / (Math.random() - 0.5)); } }", true);
        System.out.println(failed == 0 ? "PASS: " + passed + " formulas match Java " + System.getProperty("java.version") : failed + " problem(s) in " + (passed + failed) + " checks");
    }
}
