// Generated by make-strings-java.mjs from strings-cases.json. Do not edit by hand.
public class StringIndexCheck {
    // {string, method, argument (indexOf: the target; otherwise comma-separated ints), expected kind, expected value}
    static final String[][] CALLS = {
        {"planet", "substring2", "1,4", "String", "lan"},
        {"planet", "length", "", "int", "6"},
        {"planet", "charAt", "6", "throws", ""},
        {"planet", "charAt", "5", "char", "t"},
        {"planet", "charAt", "-1", "throws", ""},
        {"planet", "substring1", "6", "String", ""},
        {"planet", "substring1", "7", "throws", ""},
        {"planet", "substring1", "-1", "throws", ""},
        {"planet", "substring1", "0", "String", "planet"},
        {"planet", "substring2", "6,6", "String", ""},
        {"planet", "substring2", "0,0", "String", ""},
        {"planet", "substring2", "0,6", "String", "planet"},
        {"planet", "substring2", "4,2", "throws", ""},
        {"planet", "substring2", "-1,2", "throws", ""},
        {"planet", "substring2", "2,7", "throws", ""},
        {"planet", "substring2", "7,7", "throws", ""},
        {"Hello There", "substring2", "2,7", "String", "llo T"},
        {"Hello There", "substring1", "6", "String", "There"},
        {"Hello There", "length", "", "int", "11"},
        {"Roberts", "indexOf", "ber", "int", "2"},
        {"Roberts", "indexOf", "berz", "int", "-1"},
        {"Roberts", "indexOf", "Robe", "int", "0"},
        {"Robe", "indexOf", "Roberts", "int", "-1"},
        {"banana", "indexOf", "an", "int", "1"},
        {"banana", "indexOf", "nab", "int", "-1"},
        {"banana", "indexOf", "a", "int", "1"},
        {"red kite", "indexOf", " ", "int", "3"},
        {"red kite", "substring1", "4", "String", "kite"},
        {"Mister", "charAt", "0", "char", "M"},
        {"computer", "substring2", "3,6", "String", "put"},
        {"computer", "substring1", "8", "String", ""},
        {"computer", "charAt", "8", "throws", ""},
        {"computer", "length", "", "int", "8"},
        {"mississippi", "indexOf", "ss", "int", "2"},
        {"mississippi", "indexOf", "sip", "int", "6"},
        {"mississippi", "indexOf", "ssippi", "int", "5"},
        {"AP CSA", "substring2", "2,3", "String", " "},
        {"AP CSA", "indexOf", "csa", "int", "-1"},
        {"code", "substring2", "-1,2", "throws", ""},
        {"code", "substring2", "1,1", "String", ""},
        {"", "length", "", "int", "0"},
        {"", "charAt", "0", "throws", ""},
        {"", "substring1", "0", "String", ""},
        {"", "substring2", "0,0", "String", ""},
        {"", "indexOf", "a", "int", "-1"},
        {"abc", "indexOf", "", "int", "0"},
        {"", "indexOf", "", "int", "0"},
        {"aaab", "indexOf", "aab", "int", "1"},
    };
    // {full name, phrase, expected trace}
    static final String[][] LAB = {
        {"Ada Lovelace", "hello world", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=11;middleIndex=5;firstHalf=\"hello\";secondHalf=\" world\";switchedPhrase=\" worldhello\";middle3=\"o w\";middleChar=\" \";"},
        {"Ada Lovelace", "abcd", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=4;middleIndex=2;firstHalf=\"ab\";secondHalf=\"cd\";switchedPhrase=\"cdab\";middle3=\"bcd\";middleChar=\"c\";"},
        {"Ada Lovelace", "cat", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=3;middleIndex=1;firstHalf=\"c\";secondHalf=\"at\";switchedPhrase=\"atc\";middle3=\"cat\";middleChar=\"a\";"},
        {"Ada Lovelace", "hi", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=2;middleIndex=1;firstHalf=\"h\";secondHalf=\"i\";switchedPhrase=\"ih\";THROWS@9"},
        {"Ada Lovelace", "a", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=1;middleIndex=0;firstHalf=\"\";secondHalf=\"a\";switchedPhrase=\"a\";THROWS@9"},
        {"Ada Lovelace", "", "space=3;firstName=\"Ada\";secondName=\"Lovelace\";fullname=\"Lovelace Ada\";phraseLength=0;middleIndex=0;firstHalf=\"\";secondHalf=\"\";switchedPhrase=\"\";THROWS@9"},
        {"Cher", "hello world", "space=-1;THROWS@1"},
        {"Mary Ann Lee", "hello world", "space=4;firstName=\"Mary\";secondName=\"Ann Lee\";fullname=\"Ann Lee Mary\";phraseLength=11;middleIndex=5;firstHalf=\"hello\";secondHalf=\" world\";switchedPhrase=\" worldhello\";middle3=\"o w\";middleChar=\" \";"},
        {" Bob", "hello world", "space=0;firstName=\"\";secondName=\"Bob\";fullname=\"Bob \";phraseLength=11;middleIndex=5;firstHalf=\"hello\";secondHalf=\" world\";switchedPhrase=\" worldhello\";middle3=\"o w\";middleChar=\" \";"},
    };

    public static void main(String[] args) {
        int failures = 0;
        for (String[] c : CALLS) {
            String got = call(c[0], c[1], c[2]);
            String want = c[3] + ":" + c[4];
            if (!got.equals(want)) {
                failures++;
                System.out.println("FAIL " + q(c[0]) + "." + c[1] + ": got " + got + ", table says " + want);
            }
        }
        for (String[] c : LAB) {
            String got = lab(c[0], c[1]);
            if (!got.equals(c[2])) {
                failures++;
                System.out.println("FAIL lab " + q(c[0]) + " / " + q(c[1]) + "\n  got   " + got + "\n  table " + c[2]);
            }
        }
        int total = CALLS.length + LAB.length;
        System.out.println(failures == 0
            ? "PASS: " + CALLS.length + " calls and " + LAB.length + " lab runs match Java " + System.getProperty("java.version")
            : failures + " of " + total + " cases differ");
    }

    static String call(String s, String m, String arg) {
        String[] a = arg.split(",");
        try {
            switch (m) {
                case "length": return "int:" + s.length();
                case "charAt": return "char:" + s.charAt(Integer.parseInt(a[0]));
                case "substring1": return "String:" + s.substring(Integer.parseInt(a[0]));
                case "substring2": return "String:" + s.substring(Integer.parseInt(a[0]), Integer.parseInt(a[1]));
                case "indexOf": return "int:" + s.indexOf(arg);
                default: throw new IllegalArgumentException(m);
            }
        } catch (StringIndexOutOfBoundsException e) {
            return "throws:";
        }
    }

    // The String statements of WorkingWithStrings.java, in order. line matches the tracer's numbering.
    static String lab(String fullname, String phrase) {
        StringBuilder out = new StringBuilder();
        int line = 0;
        try {
            line = 0; int space = fullname.indexOf(" "); out.append("space=" + space + ";");
            line = 1; String firstName = fullname.substring(0, space); out.append("firstName=" + q(firstName) + ";");
            line = 2; String secondName = fullname.substring(space + 1); out.append("secondName=" + q(secondName) + ";");
            line = 3; fullname = (secondName + " " + firstName); out.append("fullname=" + q(fullname) + ";");
            line = 4; int phraseLength = phrase.length(); out.append("phraseLength=" + phraseLength + ";");
            line = 5; int middleIndex = phraseLength / 2; out.append("middleIndex=" + middleIndex + ";");
            line = 6; String firstHalf = phrase.substring(0, middleIndex); out.append("firstHalf=" + q(firstHalf) + ";");
            line = 7; String secondHalf = phrase.substring(middleIndex, phraseLength); out.append("secondHalf=" + q(secondHalf) + ";");
            line = 8; String switchedPhrase = secondHalf.concat(firstHalf); out.append("switchedPhrase=" + q(switchedPhrase) + ";");
            line = 9; String middle3 = phrase.substring(middleIndex - 1, middleIndex + 2); out.append("middle3=" + q(middle3) + ";");
            line = 10; char middleChar = phrase.charAt(middleIndex); out.append("middleChar=" + q(String.valueOf(middleChar)) + ";");
        } catch (StringIndexOutOfBoundsException e) {
            out.append("THROWS@" + line);
        }
        return out.toString();
    }

    static String q(String s) {
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }
}
